// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fnsnhylfqumbrnhjbehl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZuc25oeWxmcXVtYnJuaGpiZWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMjUxMTAsImV4cCI6MjA2MDkwMTExMH0.gLSCcRju9cPM6C_hAjYAw9xa2x4sTpe3oX9PIWrMmA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);